#!/bin/bash
#
if [ -e /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
    #
    # Reset the license checks since these questions have to be answered
    # each time the installation happens.
    #
    db_reset lg3d-core/license-declined
    db_reset lg3d-core/license-check
    db_reset lg3d-core/license-info
fi

#pushd /usr/share/lg3d/lib/linux-i686/lg3d-x11/programs/Xserver
#chown root Xorg Xvfb
#chgrp root Xorg Xvfb
#chmod 4711 Xorg
#chmod 4711 Xvfb
#/usr/share/lg3d/bin/add-lg-to-gdm
/usr/share/lg3d/bin/postinstall
