#!/bin/bash
#
# postinstall
#
# Run this script as the root user after the LG3D release has been
# installed in a local disk partition. This script gives the LG X servers
# setuid root permission. It is necessary to run this script after installing
# LG3D in order to be able to run lg3d-session and lg3d-app as a non-root user.

if [ -x /bin/arch ]; then
  ARCH=`/bin/arch`
else
  ARCH=`uname -m`
fi
if [ ${OS:-0} == 0 ]; then
  if [ ${OSTYPE:-0} == 0 ]; then
    if [ "$ARCH" == "i86pc" ]; then
      export OS="solaris"
    elif [ `uname -s` == "Linux" ]; then
      export OS="linux"
    else
      export OS="Unknown"
    fi
  elif [ "${OSTYPE}" == "linux-gnu" ]; then
    export OS="linux"
  else
    export OS=`echo ${OSTYPE} | cut -c1-7`
  fi
  if [ "$ARCH" == "x86_64" ]; then
      export ARCH="i686"
  fi
fi

if [[ "$OS" != "linux" && "$OS" != "solaris" ]]; then
  echo "This is not a Unix system. There is no postinstallaction to be performed"
  exit 0
fi

SCRIPTDIR=`dirname $0`

LGDIR=${SCRIPTDIR}/..

if [ ${OS} == "linux" ]; then
    ${LGDIR}/bin/add-lg-to-gdm
fi

cd ${LGDIR}/lib/${OS}-${ARCH}/lg3d-x11/programs/Xserver

chown root Xorg 
chgrp root Xorg 
chmod 4711 Xorg

