/*
 * JnlpFileAccessDialog.java
 *
 * Created on 12 May 2005, 14:40
 */

package org.jdesktop.lg3d.displayserver;

/**
 *
 * @author  paulby
 */
public class JnlpFileAccessDialog extends javax.swing.JDialog {
    
    private boolean grantAccess = false;
    private boolean dontAskAgain = false;
    
    /** Creates new form JnlpFileAccessDialog */
    public JnlpFileAccessDialog(java.awt.Frame parent, boolean modal, boolean readRequest, String filename) {
        super(parent, modal);
        initComponents();
        if (readRequest)
            setTitle("Read Access");
        else
            setTitle("Write Access");
        fileTF.setText(filename);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("deprecation") // ignore warning against setNextFocusableComponent()
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        fileTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        grantAccessButton = new javax.swing.JButton();
        denyAccessButton = new javax.swing.JButton();
        dontAskAgainCB = new javax.swing.JCheckBox();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setName("fileAccessDialog");
        setResizable(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(new javax.swing.border.EtchedBorder());
        jPanel1.setFocusable(false);
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);
        fileTF.setEditable(false);
        fileTF.setMaximumSize(new java.awt.Dimension(200, 19));
        fileTF.setOpaque(false);
        fileTF.setRequestFocusEnabled(false);
        fileTF.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(fileTF, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel1.setText("A Project Looking Glass component");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel2.setText("is attempting to access your local disk");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 8, 6);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        grantAccessButton.setText("Grant Access");
        grantAccessButton.setNextFocusableComponent(denyAccessButton);
        grantAccessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grantAccessButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        jPanel2.add(grantAccessButton, gridBagConstraints);

        denyAccessButton.setText("Deny Access");
        denyAccessButton.setNextFocusableComponent(dontAskAgainCB);
        denyAccessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denyAccessButtonActionPerformed(evt);
            }
        });

        jPanel2.add(denyAccessButton, new java.awt.GridBagConstraints());

        dontAskAgainCB.setText("Don't Ask Again");
        dontAskAgainCB.setToolTipText("Apply this answer to all further access");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        jPanel2.add(dontAskAgainCB, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 6);
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void denyAccessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denyAccessButtonActionPerformed
        grantAccess=false;
        dontAskAgain = dontAskAgainCB.isSelected();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_denyAccessButtonActionPerformed

    private void grantAccessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grantAccessButtonActionPerformed
        grantAccess=true;
        dontAskAgain = dontAskAgainCB.isSelected();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_grantAccessButtonActionPerformed
    
    public boolean isAccessGranted() {
        return grantAccess;
    }
    
    public boolean dontAskAgain() {
        return dontAskAgain;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JnlpFileAccessDialog(new javax.swing.JFrame(), true, true, "Test sdglkj dh gh sd fasdf v sfg df;la asd aer").setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton denyAccessButton;
    private javax.swing.JCheckBox dontAskAgainCB;
    private javax.swing.JTextField fileTF;
    private javax.swing.JButton grantAccessButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    
}
